name: Build LaTeX document

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Compile PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv_blibgober2.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv_blibgober2.pdf
