name: Build LaTeX document

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to allow pushing commits
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Compile PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv_blibgober2.tex
      - name: Commit compiled PDF
        uses: EndBug/add-and-commit@v9
        with:
          add: 'cv_blibgober2.pdf'     # path to file
          message: 'Add compiled PDF via CI'
